# Copyright (c) 2026 GitOps Manager, S.L. All rights reserved.
# -----------------------------------------------------------------------------
# bootstrap/aws — variables.tf
# -----------------------------------------------------------------------------
# All values come from terraform.tfvars.json generated by the server.
# The request shape mirrors the BootstrapRequest.Aws section exactly.
# -----------------------------------------------------------------------------

variable "management_account_id" {
  description = "AWS Management (root) account ID."
  type        = string
  validation {
    condition     = can(regex("^\\d{12}$", var.management_account_id))
    error_message = "management_account_id must be a 12-digit AWS account ID."
  }
}

variable "management_account_region" {
  description = "AWS region for management account resources."
  type        = string
}

variable "shared_services_account_id" {
  description = "AWS Shared Services account ID. ECR, Secrets Manager, S3, and agent VM deploy here."
  type        = string
  validation {
    condition     = can(regex("^\\d{12}$", var.shared_services_account_id))
    error_message = "shared_services_account_id must be a 12-digit AWS account ID."
  }
}

variable "shared_services_region" {
  description = "AWS region for shared services resources."
  type        = string
}

variable "manage_scp_automatically" {
  description = "If true, the module creates and attaches the EKSManager SCP to the OUs in org_config."
  type        = bool
  default     = true
}

variable "secrets_editing" {
  description = "If true, grants the agent role permission to update secrets in Secrets Manager."
  type        = bool
  default     = false
}

# --- Org config — OUs → accounts → allowed regions ---------------------------
# Mirrors BootstrapRequest.Aws.OrgConfig exactly.
# Key:   OU ID (ou-xxxx-xxxxxxxx)
# Value: map of AWS account ID → list of allowed regions

variable "org_config" {
  description = <<-EOT
    Organization topology. Map of OU ID → map of account ID → list of allowed regions.
    Defines which spoke accounts receive EKSManagerAdminRole via StackSet and which
    regions that role may operate in.

    Example:
    {
      "ou-xxxx-workloads" = {
        "111111111111" = ["eu-west-1"]
        "222222222222" = ["eu-west-1", "eu-central-1"]
      }
    }
  EOT
  type        = map(map(list(string)))
}

# --- Agent VM ----------------------------------------------------------------

variable "agent_name" {
  description = "Name tag for the EKS Manager agent EC2 instance."
  type        = string
  default     = "eks-manager-agent"
}

variable "agent_subnet_id" {
  description = "Subnet ID in the shared services VPC for the agent VM."
  type        = string
}

# Derived from agent_subnet_id by setup-pipeline.sh, not entered on the
# Terraform tile -- one value to supply, and the two cannot disagree.
#
# Carried because the agent's PrivateLink endpoint lives in this subnet, and the
# client-side stack has to permit that source on the NLB's 443 listener. With
# "enforce inbound rules on PrivateLink traffic" on, the security group sees the
# endpoint ENI's own address, which is in this subnet -- in an account that
# stack cannot reach, so the value has to travel rather than be looked up.
#
# Defaulted empty so an installation whose pinned vars predate this still plans.
variable "agent_subnet_cidr" {
  description = "CIDR of agent_subnet_id. Derived by setup-pipeline.sh."
  type        = string
  default     = ""
}

# agent_security_group_id intentionally removed -- looked up via a data
# source in aws/modules/agent/main.tf (fixed name
# eksmanager-bootstrap-agent-sg, created by iam/codebuild-pipeline-tf).

variable "agent_ami" {
  description = "Override AMI ID. Leave empty to use the latest Ubuntu 22.04 build automatically."
  type        = string
  default     = ""
}

variable "agent_instance_type" {
  description = "EC2 instance type for the agent VM."
  type        = string
  default     = "r5.large"
}

# --- Round-trip convenience (not consumed by any resource) ------------------
# Terraform never needs this directly -- agent_subnet_id already carries the
# subnet actually used, and AWS infers the VPC from it. Declared here only
# so pinned.auto.tfvars.json can carry it and Settings.razor's Load Pinned
# Vars can fully restore the VPC ID field, instead of losing it silently.

variable "vpc_id" {
  description = "VPC ID the agent subnet lives in. Round-trip convenience only -- see note above."
  type        = string
  default     = ""
}

# --- Agent install presigned URLs --------------------------------------------

variable "af7_bundle_download_url" {
  type      = string
  sensitive = true
}
variable "agent_upgrade_download_url" {
  type      = string
  sensitive = true
}
variable "agent_download_url" {
  type      = string
  sensitive = true
}
variable "agent_upload_url" {
  type      = string
  sensitive = true
}

# --- EKS Manager ----------------------------------------------------------

variable "app_url" {
  description = "Base URL of the EKS Manager server."
  type        = string
}

variable "client_id" {
  description = "M2M Cognito client ID used to authenticate to the EKS Manager API."
  type        = string
}

variable "cognito_url" {
  description = "Cognito token endpoint used to obtain the M2M bearer token."
  type        = string
}

variable "eks_manager_user_view_permission_set_arn" {
  description = "ARN of the EKSManagerUserView permission set, created by setup-pipeline.sh -- pinned so the agent role can look it up."
  type        = string
}

variable "eks_manager_user_admin_permission_set_arn" {
  description = "ARN of the EKSManagerUserAdmin permission set, created by setup-pipeline.sh -- pinned so the agent role can look it up."
  type        = string
}

variable "eks_manager_identity_center_role_arn" {
  description = "ARN of EKSManagerIdentityCenterRole -- EKSManagerAgentRole assumes this to create/delete account assignments."
  type        = string
}

variable "identity_store_id" {
  description = "ID of the IAM Identity Center identity store -- needed by EKSManagerAgentRole at runtime to resolve a group name to a GroupId via identitystore:GetGroupId."
  type        = string
}

variable "identity_center_resolved_region" {
  description = "Region IAM Identity Center actually lives in, auto-discovered by iam/codebuild-pipeline-tf -- needed by EKSManagerAgentRole at runtime to target SSO Admin/Identity Store API calls at the right regional endpoint."
  type        = string
}

# bearer_token removed -- was declared but never referenced by any resource
# (confirmed via grep across aws/). The server-side fetch that populated it
# was itself removed for the same reason plus being architecturally wrong
# (see BootstrapApi.cs history).

# Applied to everything this installation creates, for cost allocation.
# Pinned by setup-pipeline.sh from the Terraform tile, like the other values in
# pinned.auto.tfvars.json -- changing it means re-running that script.
#
# Reaches resources by two separate routes: Terraform-created ones through the
# provider default_tags blocks in providers.tf, and agent-created ones (the EKS
# cluster and its node groups) by way of the SSM parameters below, which the
# agent reads at create time. Terraform cannot tag the latter -- it never sees
# them.
variable "resource_tag_name" {
  description = "Tag key applied to all resources this installation creates. Empty disables the tag."
  type        = string
  default     = ""
}

variable "resource_tag_value" {
  description = "Tag value paired with resource_tag_name."
  type        = string
  default     = ""
}
